info.app:
  name: "@project.stefhani@"
  version: "@project.version1@"

logging.level.ar.edu.unlu.cursos: DEBUG
logging.level.org.hibernate.type.descriptor.sql: INFO
logging.level.org.hibernate.type: INFO
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.springframework.web: TRACE

# allow flyway to migrate/create tables on non-empty schemas

management.security.enabled: false

# URI: /manage/healthcheck
endpoints:
  health:
    sensitive: false
    id: healthcheck
  info:
    sensitive: false

spring:
  profiles.active: ${SPRING_PROFILE:local}
  application.name: "@project.stefhani@"
  thymeleaf:
    cache: false
    encoding: UTF-8

  flyway:
    baseline-on-migrate: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        id.new_generator_mappings: true

  datasource:
    driverClassName:
    url: jdbc:h2:mem:libreria-demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: scadillo
    password:
    driver-class-name:
    platform: h2
    tomcat:
      initial-size: 1
      max-active: 5
      min-idle: 1
      max-idle: 2
      max-wait: 5000
      test-on-borrow: true
      min-evictable-idle-time-millis: 300000
      validation-query: 'select 1'

  # enable H2 web console and set url for web console
  # http://localhost:8080/console
  h2:
    console:
      enabled: true
      path: /h2
server:
  error.whitelabel.enabled: false
  servlet:
    context-path: /

---
spring:
  profiles: local

---
spring:
  profiles: prod

server:
  address: 127.0.0.1
  use-forward-headers: true
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
